#!/bin/bash

set -eo pipefail

get_current_container_id() {
  cat /proc/self/mountinfo | grep "/docker/containers/" | sed -E 's/.*?\/docker\/containers\/([^/]*?).*/\1/' | head -1
}

cid="$(get_current_container_id)"
image="$(docker container inspect "$cid" --format "{{.Image}}")"
name="$(docker container inspect "$cid" --format "{{.Name}}")"

echo "elevating $cid ($name) with image $image" >&2

exec docker run -i --sig-proxy --rm --privileged --name "${name}.elevated" -e CLIENT_NETWORK -e TUN_CONTAINER_PREFIX -v /var/run/docker.sock:/var/run/docker.sock -v /proc:/proc "$image"
